[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildContext = "."

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[[services]]
name = "voice-booking-backend"

[services.healthcheck]
path = "/health"
timeout = 30

[services.variables]
PORT = "8000"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"