name: Deploy to Railway

  on:
    push:
      branches: [ main ]
      paths: [ 'backend/**' ]

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Deploy to Railway
          uses: railway-app/actions@v1
          with:
            railway-token: ${{ secrets.RAILWAY_TOKEN }}

  Workflow 2: .github/workflows/deploy-vercel.yml

  name: Deploy to Vercel

  on:
    push:
      branches: [ main ]
      paths: [ 'frontend/**' ]

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Deploy to Vercel
          uses: vercel/actions@v1
          with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }}
